### ISSUE TITLE
Check out Code To Vote

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/paravotar#1]
Nuestros amigos en [Code for Africa](https://github.com/CodeForAfrica) crearon [https://github.com/CodeForAfrica/GotToVote](https://github.com/CodeForAfrica/GotToVote). Creo que le puede ser util.

CC: @eluciano11 @Jpadilla1

**Comment by eluciano11** [comment]
@froi gracias por compartir este recurso. Ya vimos el site y creemos que podemos hacer algo parecido.
