### ISSUE TITLE
Añadir informacion de apertura de centros de inscripcion

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/paravotar#109]
**Is your feature request related to a problem? Please describe.**

Según este [tweet](https://twitter.com/ComisionadoMVC/status/1268647593594236929?s=20), los centros de inscripción comienzan a abrir este proximo lunes 7 de junio.

Estarán atendiendo solo por cita.

**Describe the solution you'd like**

ParaVotar deberia añadir los detalles de como hacer cita para inscripción electoral.

CC/ @code4puertorico/paravotar

**Comment by eluciano11** [comment]
Hey, comparto unos dibujitos (literal) que hice para modificar el site para manejar estos anuncios del COVID.

Inicialmente, estaba pensando en que podíamos añadir solo una sección de COVID a la página de Inscribete pero creo que sería mejor tener una sección aparte. Asumo que este no será el único cambio que tendremos durante el año electoral debido al COVID so  creo que agrupar esos cambios en una sección seria bueno.

En Slack también se mencionó que podiamos mostrar un label en el directorio de JIP's que tenemos actualmente para identificar las JIP's que van a estar operando con el COVID.

![photo_2020-06-05 13 44 46](https://user-images.githubusercontent.com/6109151/83907071-bc71cf00-a732-11ea-92b2-05f8befe01a6.jpeg)

![photo_2020-06-05 13 44 41](https://user-images.githubusercontent.com/6109151/83907073-bd0a6580-a732-11ea-9d4b-dd6956604b4d.jpeg)

Feedback is welcome

**Comment by eluciano11** [comment]
JIP que van a trabajar desde el lunes

https://twitter.com/ceedepuertorico/status/1269037315902627841

**Comment by eluciano11** [comment]
![sketch-saca-tu-cita](https://user-images.githubusercontent.com/6109151/83934037-a2101380-a77b-11ea-9c80-08de11ca52f7.png)

**Comment by froi** [comment]
Hace un tiempo teníamos un documento con todos los precintos electorales de PR. ¿Esta lista se podrá utilizar para esto?

**Comment by eluciano11** [comment]
Yup, la teníamos pero decidimos removerla por ahora pq casi ninguno va a estar abierto por el momento.

Closing this for now. Ya estos updates están en el site.
