### ISSUE TITLE
Reforma electoral en Puerto Rico

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/paravotar#111]
Hoy vi un [tweet](https://twitter.com/juandalmaupr/status/1268748966398746624?s=21) de Juan Dalmau sobre una reforma electoral. No estoy claro en que consta, pero creo que es algo del cual debemos estar pendientes.

Si encuentro algo sobre esta reforma lo añado aqui.

**Comment by eluciano11** [comment]
Links que se han compartido en Slack:

https://www.noticel.com/legislatura/ahora/20200531/guerra-interna-en-el-pnp-salpica-la-reforma-electoral-segun-populares/

https://www.noticel.com/legislatura/ahora/top-stories/20200311/estos-son-los-cambios-mas-importantes-del-nuevo-codigo-electoral/

**Comment by eluciano11** [comment]
@froi por el momento no hemos pensado en los posibles cambios que la reforma electoral pueda traer. Si la reforma se convierte en ley nos comenzamos a preocupar por esto...

**Comment by froi** [comment]
Fair enough. @eluciano11 quieres cerrar este issue entonces?

**Comment by eluciano11** [comment]
yes, lo abrimos de nuevo si lo aprueban

**Comment by eluciano11** [comment]
estaba esperando no tener que reabrir este issue pero ... it happened. 😞 

https://mobile.twitter.com/fortalezapr/status/1274440708750028803

**Comment by froi** [comment]
Que mal. El enfoque al voto integro es preocupante.

**Comment by jamesxv7** [comment]
A parte de entender el proyecto y educar ¿Qué tipo de ayuda se necesita? Como se está pensando cubrir a través del webapp?

**Comment by eluciano11** [comment]
Buena pregunta. Honestamente, esto no lo tenemos tan definido. Parte del trabajo de este issue es identificar cómo la reforma electoral afecta directamente al votante. Idealmente, conseguimos a alguien que tenga conocimiento sobre el proyecto de ley pero si no lo logramos encontrar nos podemos basar en reportajes como los que compartió @froi.

Por lo que he podido leer, la reforma electoral es bastante grande y hay ciertas cosas que afectan directamente en el voto de los ciudadanos. Por ejemplo, vi un reportaje en el que dijeron que la reforma electoral elimina la intención de voto. Eso significa que cuando votes, la marca que hagas TIENE que estar en el encasillado correcto o no cuentan el voto.

Dicho eso, yo creo que los first steps para este ticket son los siguientes:
- [ ] Buscar cómo la reforma electoral afecta directamente al votante. Quizás @rebelwarrior o alguien en Slack nos puede dar una mano con esto.
- [ ] Basando en la info que encontremos debemos identificar dónde es el mejor lugar para mostrar estos cambios en el site. Puede ser que tengamos que añadir una sección nueva con los cambios de la reforma electoral o puede ser que podamos añadir esta información a las secciones existentes.
