### ISSUE TITLE
Development Steps Update

### ISSUE THREAD

**Issue by jamesxv7** [Code4PuertoRico/paravotar#113]
__Please write your feedback as detailed as possible bellow.__
Seems development instructions are a little bit outdate
![image](https://user-images.githubusercontent.com/121668/84071080-22608f80-a99b-11ea-8815-9bd35299999e.png)

__Have you thought about any possible solutions or ways to approach this? If so please let us know!__
I could create a PR with the steps required to spin site new version.

**Comment by eluciano11** [comment]
Good catch! Seria bueno tener un PR de esto para hacer el proceso más simple para otras personas.

Para manejar la dependencia de Gatsby tenemos dos opciones:
1. Instalar el CLI de Gatsby.
2. Instalar Gatsby como un dev dependency del proyecto. Entiendo que al hacer esto eliminaríamos la necesidad de tener Gatsby global.

@Jpadilla1 @jamesxv7 que creen? Tienen alguna preferencia para manejar esto?

**Comment by jamesxv7** [comment]
No soy experto en Gatsby y actualmente mi dev setup es a través de un docker container o una máquina virtual. Así que no me afecta mucho. No estoy seguro como afectaría tener esta dependencia tan heavy como un dev dependency a la hora de hacer deployment a través de un CI/CD system.
