### ISSUE TITLE
Add calendar reminder v2

### ISSUE THREAD

**Issue by eluciano11** [Code4PuertoRico/paravotar#140]
**Is your feature request related to a problem? Please describe.**
Actualmente, nuestros recordatorios están programados para 3 semanas antes de la fecha límite para inscribirse. @krismuniz propuse hacer una segunda iteración en donde el usuario pueda escoger la fecha del recordatorio. Para hacer esto necesitamos un servicio que genere un ics que el usuario pueda descargar y añadir a su calendario.

Comment original:
https://github.com/Code4PuertoRico/paravotar/issues/44#issuecomment-669646093

CC/ @code4puertorico/paravotar

**Comment by krismuniz** [comment]
Tomaré esta tarea 🙋🏻‍♂️

**Comment by krismuniz** [comment]
Imagino que comienza en https://github.com/code4puertorico/paravotar-api

**Comment by eluciano11** [comment]
Yes, creo que necesitamos a @Jpadilla1 para poder deploy a la cuenta de AWS que tenemos ahora mismo.

**Comment by krismuniz** [comment]
Definitivo. Puedo desarrollar el lambda localmente, probarlo en mi own AWS environment y cuando esté listo se lo paso a @Jpadilla1 y él continúa con el resto de la tarea

**Comment by krismuniz** [comment]
Lo bueno es que no se necesita acceso a ningún data source. So, it's a non-blocker.

**Comment by eluciano11** [comment]
Yup, sounds good to me!
