### ISSUE TITLE
Update absentee voter and early voter deadlines and docs.

### ISSUE THREAD

**Issue by eluciano11** [Code4PuertoRico/paravotar#142]
Absentee voter doc:
http://ww2.ceepur.org/sites/ComisionEE/es-pr/EducacionyAdiestramiento/Solicitudes/Solicitud%20Voto%20Ausente%20Elecciones%20Generales%20y%20Plebiscito%202020.pdf

**Comment by matteing** [comment]
now i'll talk later, finishing some modules de quim y me quiero ma.tar.

te juro que lo unico que estoy pensando viendo estos videos es en tus besos y cuidao que de vez en cuando pienso de lo que me estan enseñando...

**Comment by matteing** [comment]
Stumbled upon this issue a couple of minutes ago -- indeed, the links are broken.

(p.s. ignore a previous comment, accidentally ctrl-v'd and posted the wrong text...)

**Comment by eluciano11** [comment]
lol, dale. voy a fix it ahora.

**Comment by matteing** [comment]
Thanks so much!
