### ISSUE TITLE
Ejemplo de voto por nominación directa

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/paravotar#145]
__Please write your feedback as detailed as possible bellow.__

¿Creen que seria bueno tener un ejemplo de nominación directa? ¿Si colocan un nombre como nominación directa, tienen que hacer la marca también?

![image](https://user-images.githubusercontent.com/1918027/92980464-55b42e00-f464-11ea-8b76-a1a98e36e523.png)

**Comment by eluciano11** [comment]
Sí, creo que deberíamos añadir ese tab.
