### ISSUE TITLE
Upload data de papeletas

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/paravotar#164]
Creamos un staging area en Google Drive para ir almacenando la data de las papeletas. Iremos colocando todo aqui para entonces poder determinar próximos pasos.

Estaremos dando más detalles en este issue.

Plan:

1. Por cada papeleta que le hagamos parsing con el [extractor](https://github.com/Code4PuertoRico/paravotar-api/tree/master/papeleta-pdf-extractor) vamos a subir el resultado del OCR con las imagenes a google drive.
2. Para consistencia, la estructura que vamos a usar es la siguiente:
    - estatal
           - data.json
           - images
    - "municipio"
           - data.json
           - images
    - "municipio"-legislativa-"precinto"
           - data.json
           - images
3. El data.json tendrá un arreglo de arreglos que representa la papeleta con el siguiente contenido por cada celda:
 ```json
{
    "img": "<path>-<name>.jpg",
    "ocrResult": "<contenido extraido de la imagen>",
    "logoImg": "<path>-<name>.jpg"
}
```
4. Cuando tengamos todas las papeletas listas, podemos pensar en como seria mejor pedir ayuda de la comunidad para verificar el contenido.

**Comment by chrisrodz** [comment]
Ya todas las papeletas han sido parsed y la data está en Google Drive!

Hubo otro esfuerzo de extraer los nombres de los candidatos con las papeletas que se puede ver aquí: https://github.com/Nosferican/CandidatosEleccionesGeneralesPR2020/tree/main/data

Queda pendiente el punto 4 aquí de como vamos a verificar el contenido y creemos que se puede usar ese esfuerzo linked arriba para arrancar con una mejor base ya que la data está un poco más clean que el resultado del OCR pero estamos todavía brainstorming la mejor manera de hacerlo.

Podemos close this one out y abrir uno nuevo para coordinar el esfuerzo de la validación? @froi @Jpadilla1

**Comment by froi** [comment]
@chrisrodz De acuerdo con cerrar este issue en favor de uno que trabaje el tema del punto cuatro.
> Cuando tengamos todas las papeletas listas, podemos pensar en como seria mejor pedir ayuda de la comunidad para verificar el contenido.

Lo idea es que se crea el issue nuevo con los detalles, se le haga mención aqui o en él para mantener una linea de como fue que llegamos a las decisiones.

**Comment by froi** [comment]
Gracias pro crear #165 @chrisrodz 🎉 🌮 . 

Closing this one out.
