### ISSUE TITLE
Validación y verificación de papeletas parsed

### ISSUE THREAD

**Issue by chrisrodz** [Code4PuertoRico/paravotar#165]
Continuación de #164 , ya que se hizo parse de todas las 180+ papeletas ahora queremos validar esa data. Tenemos un segundo resultado de OCR gracias a otro esfuerzo ciudadano aquí: https://github.com/Nosferican/CandidatosEleccionesGeneralesPR2020/tree/main/data

Queremos asegurar que el `data.json` de cada papeleta que se genero este correcto para poder usarlo en el next step de Practicar el voto.

Estamos todavía brainstorming la manera más efectiva de hacer esta validación, y este issue va a ser updated cuando se haya decidido

**Comment by eluciano11** [comment]
Ya terminamos con esto. Gracias por la ayuda!
