### ISSUE TITLE
Ballot Validator library

### ISSUE THREAD

**Issue by Jpadilla1** [Code4PuertoRico/paravotar#172]
**Is your feature request related to a problem? Please describe.**
We require a ballot validator library where we can provide feedback to the user if the selections they have made are valid or not.

**Describe the solution you'd like**
I have a proposed solution in this PR #171 

**Additional context**
The version linked here #171 can be described as a rule based approach. Where we have a validate function that accepts one of 3 [Ballots](https://github.com/Code4PuertoRico/paravotar/pull/171/files#diff-be0085ef5a64f2fdd02c1b8fd6dcfaa7R8-R27) and a [BallotType](https://github.com/Code4PuertoRico/paravotar/pull/171/files#diff-be0085ef5a64f2fdd02c1b8fd6dcfaa7R31). The return value is an object describing the status of the validation and the allowed & denied outcomes.

The way the rules work is by using a [RuleGroup](https://github.com/Code4PuertoRico/paravotar/pull/171/files#diff-aa2f83111b0683eb1c92861418b6e328R7) which has an array of rule instances to run against the ballot. Some rules are shared in between ballots and each rule only validates 1 thing. Example, the [NoEmptyBallotRule](https://github.com/Code4PuertoRico/paravotar/pull/171/files#diff-49967b68c34d95614479ef313a3c18d2R5) checks if the ballot is empty. If it is the rule returns a deny outcome which means the ballot in invalid.

Rules of writing a rule:

- Should inherit from [BaseRule](https://github.com/Code4PuertoRico/paravotar/pull/171/files#diff-83951e93c15af94da22b3efb16d88099R3)
- Should only check 1 thing
- Returns an object with the outcome and an optional metadata object
- Should only validate against cases where the ballot would be invalidated

Example output:

```json
{
  "status": "failure",
  "outcomes": {
    "allowed": [
      {
        "outcome": "allow",
        "ruleName": "NoMoreThanOnePartySelectedRule"
      }
    ],
    "denied": [
      {
        "outcome": "deny",
        "ruleName": "NoEmptyBallotRule"
      }
    ]
  }
}

```

CC/ @code4puertorico/paravotar

**Comment by froi** [comment]
This looks good and @eluciano11 has given his 👍🏼  in #171.

I do have one question. Are you looking to implement a rules engine? If so https://github.com/froi/simple-rules-engine/ might help you with some ideas, boilerplate, or just a a dependency to use.

**Comment by Jpadilla1** [comment]
lol yeah this is pretty much a rules engine

**Comment by Jpadilla1** [comment]
For clarity we are moving forward with this approach #171
