### ISSUE TITLE
Validación de la data en las papeletas

### ISSUE THREAD

**Issue by eluciano11** [Code4PuertoRico/paravotar#186]
Ya la data de las papeletas están en nuestros servidores. Ahora necesitamos verificar si hemos cometido algún error y si la data se extrajo correctamente. Para eso creamos un Spreadsheet con links a las papeletas originales y links a nuestro site.

Necesitamos verificar que las imagenes de los candidatos y partidos estén mostrandose correctamente y los nombres de los candidatos estén bien.

Si se encuentra algo mal en alguna papeleta debemos añadir un google form que creamos. Allí podrán añadir el id de la papeleta (esto está en la primera columna del spreadsheet), ejemplo de lo que esta mal y screenshot (si es posible/necesario).

Por favor, cuando procesen una papeleta cambien el color de la fila y añadan un comentario al final en donde se indique si necesitamos arreglar algo en la papeleta.

Spreadsheet:
https://docs.google.com/spreadsheets/d/1_7TK_Pm7hUchiJqkURnn33YiEanSQRcFXmdZJKyDc8M/edit#gid=664615550

Google Form:
https://docs.google.com/forms/d/e/1FAIpQLScYapnY9gMVPW7Jnr1PgZPM9kFQggtxefivDe__8R7IYr95oA/viewform?usp=sf_link

**Comment by eluciano11** [comment]
El issue #165 también tiene que ver con esto.

**Comment by chrisrodz** [comment]
Separé una hora hoy por la noche para darle un stab a la validación utilizando el spreadsheet. Voy a estar online 7pm-8pm (hora Puerto Rico) dándole a esto a ver cuánto se puede hacer en ese tiempo.

**Comment by lafonj** [comment]
Empecé a mirarlas y el error que encontré afecta todas la papeletas. Hice un PR para arreglarlo: https://github.com/Code4PuertoRico/paravotar/pull/190 . Quieren poner una opción en el spreadsheet para q la gente puedan poner un link al PR q arregla los errores? De esa manera tal vez no tengan q ir feedback por feedback arreglándolos.

**Comment by eluciano11** [comment]
Hola @lafonj, de nuevo, gracias por el PR! La idea de poner un PR con los fixes nos parece excelente pero en este momento no tenemos la data de las papeletas en el repo. Tengo entendido que @Jpadilla1 haciendo los fixes y subiendolos a s3 poco a poco.

**Comment by lafonj** [comment]
Ah asumí q estaba ahí. Bueno, pronto me vuelvo a meter a ver si quedan papeletas

**Comment by eluciano11** [comment]
Ya terminamos con esto. GRACIAS A TODOS Y TODAS POR SU AYUDA!
