### ISSUE TITLE
Feedback for Alpha Version

### ISSUE THREAD

**Issue by eluciano11** [Code4PuertoRico/paravotar#207]
Este issue busca recoger el feedback que la version inicial de practica. Pueden escribir sus comentarios y sugerencias aquí para poder discutirlas y mejorar el producto final.

**Comment by eluciano11** [comment]
Feedback de @rnegron:
1. la sección de "Practica tu voto" creo debería salir abajo de "¿Cómo votar?" en el sidebar y también creo que debería estar más resaltada de lo que está. Yo pondría las dos secciones de arriba en un solo "hero" y la sección de Práctica la haría más grande
2. no creo que votar íntegro debería marcar también a los candidatos individuales. en una papelete de verdad no se marcarían. la X que se marca debería ser más clara si la idea es orientar a la persona que se emitiría ese voto.
3. el "estatus de su papeleta: válida" lo cambiaría por un :white_check_mark: . igual "invalida" por :x:
4. no encuentro cómo regresar y escoger otro tipo de papeleta para prácticar
5. sugerencia: tener un status menu sticky cuando entras a la papeleta que contenga los datos

**Comment by eluciano11** [comment]
#3 y #5 deben estar arreglados

**Comment by froi** [comment]
Additional feedback from test users:

1. Algo que considero q deben trabajar para que no se mal interprete es que al momento de practicar el voto no debe decir submit. Creo que es mejor que diga validar. El submit se puede interpretar como que ustedes almacena esa info.
1. Cuando pones un precinto no existente te tira un failure. Debería decir un mensaje de precinto invalido o algo así.

**Comment by froi** [comment]
@Code4PuertoRico/paravotar 

Tengo este feedback:

> mira es que yo tengo una duda y no se como tu lo veas.

![image](https://user-images.githubusercontent.com/1918027/95922191-b8a92580-0d80-11eb-9aff-807ed75a70be.png)

> cuando marcas integro las X de abajo se marcan
> entiendo que es para darte la impresion por lo que estas votando
> y entiendo el mensaje
> pero la poblacion la entendera?
> esa es mi duda. no se como los demas lo tomarian
> puede que sea yo, pero deben de ustedes como que poll eso, y ver.
> creo que la marca es como dejandote saber por quien estas votando. Pero no se si se mal interpreta

La pregunta es, cuando se vota integro se tiene que marcar todos los candidatos del partido? Creo que no es el caso pero no estamos segur@s?

**Comment by eluciano11** [comment]
Cuando votas integro no tienes que marcar los candidatos en la papeleta. La idea con ese features es que las personas entiendan por quien estarían votando y cómo funciona el voto mixto. Básicamente, es un voto integro del cual te sales fuera de la papeleta para votar por otros candidatos y le restas a los últimos candidatos del partido que seleccionaste.

**Comment by eluciano11** [comment]
Feedback:

1. Cuando seleccionas un partido para voto mixto y ya hay un candidato seleccionado explicitamente para una posición no debemos adjudicar el voto.

✅  2. Write In vote support.

3. Estado de la papeleta en el fullscreen modal.

✅  4. Esta saliendo un write in candidate demás en senadores por acumulación.

✅  5. Decent loading screen

**Comment by giangonz** [comment]
Hola. En el campo para poner el precinto, pongan un pop-up a este enlace:
http://168.62.166.179/Informe%20Estadistico/Redist2000/Mapas%20de%20los%20Precintos%20Electorales.html

Creo que lo hace mas facil
