### ISSUE TITLE
Error al intentar practicar el voto

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/paravotar#243]
**Describe the bug**

Al escoger un pueblo para practicar el voto la pagina me devuelve el error `Oops! No logramos encontrar tu información.`.

**To Reproduce**
1. Go to `Practiva tu voto`
2. Click on `Numero de precinto o pueble`
3. Escoge un pueblo

**Expected behavior**

Que salga la papeleta del pueblo escogido.

**Screenshots**

<img width="1599" alt="image" src="https://user-images.githubusercontent.com/1918027/130988543-08881bfe-533f-4449-b35b-1f9464cd7a89.png">

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all

**Additional context**

CC/ @code4puertorico/paravotar

**Comment by Jpadilla1** [comment]
This has been fixed.

### Root cause

Certificates for api.paravotar.org & cdn.paravotar.org expired in AWS and were not available for renewing. We had to setup new certificates to get them back online.
