### ISSUE TITLE
Add calendar reminder section

### ISSUE THREAD

**Issue by eluciano11** [Code4PuertoRico/paravotar#44]
## Description
Este feature lo que busca es que los usuarios puedan descargar un calendar event que les sirva como un reminder de la fecha límite (14 de septiembre 2020) que tienen para inscribirse.

Inicialmente, ese feature puede tener 3 fechas estáticas y para una segunda versión podemos mejorarlo para que el usuario pueda escoger el día y la hora del reminder.

Pensamos que el formato de ICS nos puede ayudar a crear este feature. Según tengo entendido, Outlook, Google Calendar y iCalendar pueden manejar este tipo de file.
https://fileinfo.com/extension/ics

## Why
Porqué crear un calendar reminder y no enviar una notificación por mensaje de texto o email? Simple, desde el principio del proyecto decimos no recolectar ningún tipo de PII (Personal Identifiable Information) para evitar cualquier tipo de problema con la privacidad de los usuario.

## Design
![image](https://user-images.githubusercontent.com/6109151/75124834-1836b180-5688-11ea-82ad-4673e53db6b0.png)

**Comment by LuisRamos10** [comment]
I could help with this. I have a few questions on how exactly it will work. @eluciano11 podemos hablarlo?

**Comment by eluciano11** [comment]
@LuisRamos10 yes, podemos hablarlo por Slack! Voy a escribirte por allá.

**Comment by froi** [comment]
FYI

La fecha limite para inscribirse es 14 de septiembre 2020.

**Comment by krismuniz** [comment]
Creo que puedo tomar esta tarea!

**Comment by eluciano11** [comment]
@krismuniz awesome! go for it!

**Comment by krismuniz** [comment]
Ya hice el research preliminar para delinear el "scope".

### Primera iteración

Crear un `.ics` file (e.g. `inscribete.ics`), guardado en `/src/assets/` y añadir un botón en la página principal que descargue el file.

### Segunda iteración

Más sofisticada. Crear un micro-service / serverless function que genere los `.ics` on the fly en base a un HTTP request. Ya he hecho research preliminar, parece sencillo: https://github.com/krismuniz/ics-service

**Comment by krismuniz** [comment]
Necesitamos ponernos de acuerdo en un par de cosas para generar el evento del primer `.ics` estático

1. Título del Evento (e.g. Fecha límite para inscribirse para votar)
2. Descripción del evento (quizá información extra, links, instrucciones, etc)
3. Recordatorios "default" (tengo en mente 1 día antes, 1 semana antes, y 2 semanas antes)

**Comment by eluciano11** [comment]
@krismuniz primero, gracias por trabajar en esto! Awesome work! 🔥 🔥 💪 

Estaba mirando el PR #136 y entiendo que los títulos, descripción y fechas para los reminders están bien así que podemos merge y deploy con ellos.

Para la segunda iteración, podemos añadir los lambda functions al repo que tenemos de [para-votar-api](https://github.com/Code4PuertoRico/paravotar-api). Allá estamos agrupando todos los lambdas del proyecto así que entiendo que ese es el lugar ideal para esto. Dicho eso, para deploy esos lambdas vamos a necesitar la ayuda de @Jpadilla1 porque él es quien tiene la cuenta de AWS que estamos usando.

@krismuniz qué te parece si manejamos la segunda fase en un issue aparte?

**Comment by krismuniz** [comment]
@eluciano11 Dale, me parece bien!
