### ISSUE TITLE
Fix scroll to top bug

### ISSUE THREAD

**Issue by eluciano11** [Code4PuertoRico/paravotar#45]
On mobile, when you open an accordion the scroll position is going to the top. Instead of doing this it should stay in the same position.

**Comment by Jpadilla1** [comment]
I tried to fix it using this, but got confused when integrating. https://github.com/pbeshai/use-query-params in the examples the UI rerenders but when I tried it, it didn't rerender.

**Comment by eluciano11** [comment]
Hmm, investigué un poco y parece que el scroll to top no es un bug, es un feature de reach router. En reach router cuando cambias el url programaticamente ellos te cambian el foco de la pagina para que vaya al principio. Ellos tiene un workround y es crear un secondary router, con paths distintos pero creo que en nuestro caso es un overkill.
