### ISSUE TITLE
V1 pre-release community feedback

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/paravotar#59]
Gracias por regalarnos tu tiempo y darnos esta retroalimentación sobre https://www.paravotar.org/! ❤️ 

Para someter su retroalimentación por favor añada un comentario en este issue.

Gracias nuevamente!!!!

**Comment by rubenvarela** [comment]
Saludos a todos! 

Bueno, yo lately he estado trabajando bastante con accessibility so es a lo que primero mi mente va.

Headings, no hay h1. Cada sección tiene un h3 followed by an h2.

En el flexbox de 4, opacity 0 como quiera es picked up por screen readers pero con espacios en blanco. `display:none;` no. Si se puede cambiar eso, la transición seria del titulo al botón no a elementos en blanco y luego al botón.

Las letras de los filtros, no tienen explicación de que son o como utilizarlos. Falta texto explicando que hacer ahí. Si no simplemente sale 'button, a' y cuando cambias 'button, b'. 

Para los dynamic sections, usualmente hay contenido que se añade para dejar saber que hay contenido nuevo. Seria util especialmente en el grid con el botón ya que el contenido aparece antes del botón.

**Comment by Jpadilla1** [comment]
Saludos @rubenvarela!

Gracias por el feedback! Accessibility es super importante y puede ser una discussion bastante extensa mientras se desarolla el site. Cree un issue aparte para highlight it mejor en la lista de issues. #63

**Comment by rubenvarela** [comment]
@Jpadilla1 Suena perfecto.

**Comment by froi** [comment]
Retroalimentación tambein fue dado en el Issue #60

**Comment by jpadilla** [comment]
<img width="1215" alt="Screen Shot 2020-03-05 at 5 31 57 PM" src="https://user-images.githubusercontent.com/83319/76032170-4aa5a180-5f07-11ea-9abc-52d879be013c.png">

Esto de **San Juan 1**, **San Juan 1-A**, etc, me pareció raro, pues no se cual es la diferencia ni pq hay multiples. Se pueden consolidar bajo **San Juan**, listar las multiples localizaciones y maybe añadir una nota de pq hay multiples y como se a donde llamar/visitar?

Other than that, gracias por todo esto, buen trabajo! ❤️

Update: Vi **Todo voto practicado en esta plataforma es completamente anónimo y privado.** en el footer y me preguntaba donde podia practicar el voto. v2?

**Comment by eluciano11** [comment]
> Esto de San Juan 1, San Juan 1-A, etc, me pareció raro, pues no se cual es la diferencia ni pq hay multiples. Se pueden consolidar bajo San Juan, listar las multiples localizaciones y maybe añadir una nota de pq hay multiples y como se a donde llamar/visitar?

💯 Tenemos un card para group them pero no lo hemos cerrado todavia. See #46.

En #60 @rebelwarrior mencionó que hay JIP's que atienden a personas de ciertas zonas. Creo que debemos highlight eso también en el UI.

>Update: Vi Todo voto practicado en esta plataforma es completamente anónimo y privado. en el footer y me preguntaba donde podia practicar el voto. v2?

Yessir, v2 o v3.

**Comment by Jpadilla1** [comment]
> Update: Vi Todo voto practicado en esta plataforma es completamente anónimo y privado. en el footer y me preguntaba donde podia practicar el voto. v2?

Como @eluciano11 menciono, v2 o v3. Si les interesa ver el prototipo funcional sin diseño pueden verlo aqui https://www.paravotar.org/practica-tu-voto/. Agradecemos ideas, sugerencias, etc sobre practica en otro issue para no distraer este thread sobre v1 pre-release.

**Comment by jamesxv7** [comment]
¿Cuál es el proceso para someter pull requests (PR)?

Mi interesa apoyar el proyecto pero no quisiera trabajar sobre ítems que ya estén asignados o que no sean de tanta prioridad.

**Comment by eluciano11** [comment]
Hola @jamesxv7 gracias por ofrecerte a ayudar!

Ahora mismo no tenemos un proceso definido para someter PR's. Tenemos varios tickets que están identificados con `help-wanted`. En este momento, ninguno de ellos están asignado nadie por lo que puedes trabajar el que prefieras. 

Yo pienso que la prioridad para los tickets que tienen `help-wanted` es la siguiente: #44, #84 y #63. #63 esta última no pq sea menos importante sino pq añadimos ciertas mejoras y hacen el site "usable" para alguien utilize screen readers pero sin dudas puede mejorarse más.

Si tienes sugerencias para mejorar el site de alguna manera también es bienvenida.

**Comment by froi** [comment]
@jamesxv7 dale un vistazo al [CONTRIBUTING.md](https://github.com/Code4PuertoRico/paravotar/blob/master/CONTRIBUTING.md). El proceso es simple y sigue los que se considera “normal” para un proyecto open source en GitHub.

Si tienes duda de como hacer estas cosas dejame saber aqui, estamos para ayudar 😄

**Comment by jamesxv7** [comment]
@eluciano11 & @froi estoy trabajando en el #84. Esta noche espero tener listo el PR para evaluación.
