### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by rebelwarrior** [Code4PuertoRico/paravotar#60]
![electoral](https://user-images.githubusercontent.com/839013/76028593-eed81a00-5f00-11ea-9815-d0103e66bbfc.png)

1. Según mis notas no se necesitan tantos documentos en la mayoría de los casos. Por ejemplo:
Si Nació en PR no esta ya registrado (y tiene la edad) necesita los siguientes docs:
**ninguno**
Necesita saber: Nombre completo, estatura, si tiene hermano gemelo, dirección postal, núm. de tel de contacto, y saberse su número de seguro social. 
También su dirección postal física (lo cual poca gente sabe) ó traer evidencia de la dirección si no esta en el récord electoral (lo cual es bien raro). ¿Cuándo se necesita la evidencia de dirección entonces? Cuando alguien _ya está registrado_ y necesita cambiar de pueblo. Entonces si necesita traer evidencia de dirección pero de acuerdo lo que yo entendí el propósito principal del proyecto eran inscripciones nuevas. 
No se necesita traer la tarjeta de seguro social, pero sí se necesita **saber** el número y eso es _todo el mundo_. 
La licencia de conducir (o cualquier identificación oficial con foto) es _recomendado_ llevar porque si se va la luz y no hay sistema la necesitan para identificar a la persona.

2. Botón de verificar mi estatus debería
![Screen Shot 2020-03-05 at 4 57 23 PM](https://user-images.githubusercontent.com/839013/76029456-838f4780-5f02-11ea-92a9-ea6661171aeb.png)
 indicar con un ícono que te va a mandar al otro website. 

3. Las direcciones de los centros no indican cuales JIPs son para toda la isla (o sea que pueden recibir a alguien de toda la isla, como el que esta en Hato Rey en la comisión) comparados con los otros que no. 
![Screen Shot 2020-03-05 at 5 00 45 PM](https://user-images.githubusercontent.com/839013/76029633-e254c100-5f02-11ea-8ad6-38ed4a7a9034.png)

4. No hay ninguna diferencia entre alguien que tiene 18 años (o mas) y alguien que los cumple en las elecciones del cuatrenio. Es mas en puerto rico si uno cumple 18 en o antes de las elecciones se le extiende el derecho a votar en las primarias aunque no haya cumplido los años todavía. Si tiene derecho a votar en las elecciones tiene derecho a votar en las primarias.

**Comment by Jpadilla1** [comment]
Gracias por el feedback! Pregunta en la # 3. En donde se puede encontrar cuales JIP son para toda la isla?

**Comment by rebelwarrior** [comment]
Puedo averiguar la CEE tiene una lista. Son pocos.

**Comment by eluciano11** [comment]
Hey, gracias por el feedback!

Tengo unos comentarios/dudas sobre algunas partes del feedback:

> 1. Según mis notas no se necesitan tantos documentos en la mayoría de los casos.
Si Nació en PR no esta ya registrado (y tiene la edad) necesita los siguientes docs:
ninguno

Yes, me fije en eso cuando es estaba implementandolo pero encontramos otros recursos que mencionaban que podían necesitar esos documentos así que optamos por añadirlos (better safe than sorry). Un recurso que me compartió Layshi (la diseñadora) fue este pero entiendo que uso algo de la CEE también.
https://www.instagram.com/p/B71rhe_BDei/?igshid=hja66dvido7w

>Necesita saber: Nombre completo, estatura, si tiene hermano gemelo, dirección postal, núm. de tel de contacto, y saberse su número de seguro social.

Creo que esto tenemos que encontrar un buen lugar para ponerlo pq supongo entiendo que todo el mundo lo va a necesitar.

>También su dirección postal física (lo cual poca gente sabe) ó traer evidencia de la dirección si no esta en el récord electoral (lo cual es bien raro).

Una persona que este nunca se ha registrado no debería tener record electoral asi que por default va a necesitar evidencia de la dirección, correcto?

>¿Cuándo se necesita la evidencia de dirección entonces? Cuando alguien ya está registrado y necesita cambiar de pueblo. Entonces si necesita traer evidencia de dirección

Esta información seria bueno tenerla en la sección de verifica tu estatus pq mencionamos el caso que te hayas mudado.

> de acuerdo lo que yo entendí el propósito principal del proyecto eran inscripciones nuevas.

Sí, a esta parte le ha crecido un poco el scope pero entiendo que son casos validos.

---

> 2. Botón de verificar mi estatus debería

Yes, tienes toda la razón.

---

>4. No hay ninguna diferencia entre alguien que tiene 18 años (o mas) y alguien que los cumple en las elecciones del cuatrenio. Es mas en puerto rico si uno cumple 18 en o antes de las elecciones se le extiende el derecho a votar en las primarias aunque no haya cumplido los años todavía. Si tiene derecho a votar en las elecciones tiene derecho a votar en las primarias.

Quisiera double check esto. Esto va a parecer una referencia bien extraña pero en este video la empleada de la comisión dice que tienes que tener 18 *en o antes del 3 de noviembre* para poder sacar la electoral. Minuto 1:07.
https://www.instagram.com/tv/B71s4K3Hwt_/?utm_source=ig_web_copy_link

**Comment by eluciano11** [comment]
>2. Botón de verificar mi estatus debería

Fixed en #62

**Comment by rebelwarrior** [comment]
El récord electoral al que me refiero es el que marca en que pueblo esta una casa. Ellos usan ArcGIS (y QGIS) para dibujar los limites (y en par de casos el limite cae en una casa y el récord demuestra en que lado de la linea cae la casa, etc.) y asi saben en que distrito y municipio cae la casa.

O sea realmente solo son casas nuevas que no se han incluido en sistema de la CEE; en estos casos necesitan la evidencia de residencia física. 

Si la persona no se ha registrado pero la casa ya esta en el récord no necesita evidencia para registrarse típicamente. 

> 
>     También su dirección postal física (lo cual poca gente sabe) ó traer evidencia de la dirección si no esta en el récord electoral (lo cual es bien raro).
> 
> Una persona que este nunca se ha registrado no debería tener record electoral asi que por default va a necesitar evidencia de la dirección, correcto?

**Comment by eluciano11** [comment]
>El récord electoral al que me refiero es el que marca en que pueblo esta una casa. Ellos usan ArcGIS para dibujar los limites y en par de casos el limite cae en una casa y el récord demuestra en que lado de la linea cae la casa, etc.
Que realmente son solo casa nuevas que no se han incluido en sistema de la CEE que pueden requerirlo la evidencia de residencia física.
Si la persona no se ha registrado pero la casa ya esta en el récord no necesita evidencia para registrarse típicamente.

Gracias por aclarar esto, no sabia estos detalles!

**Comment by eluciano11** [comment]
@rebelwarrior el PR #73 hay par de fixes con fixes de tus comentarios. Añadí la información basica que debes saber per voter profile y aclaré qué era requerido/recomendado vs qué es opcional y cuando lo puedes necesitar

Aca esta el [Deploy preview](https://deploy-preview-73--paravotar.netlify.com/).

**Comment by eluciano11** [comment]
Closing ya que las sugerencias de este PR fueron deployed (excepto el punto número 4) en #73

**Comment by eluciano11** [comment]
cree #79 para track el punto `#3` aparte.
