### ISSUE TITLE
Accessibility Audit 

### ISSUE THREAD

**Issue by Jpadilla1** [Code4PuertoRico/paravotar#63]
https://github.com/Code4PuertoRico/papeleta-pr/issues/59#issuecomment-595572132

**Comment by froi** [comment]
Me when I saw that this is already in an issue

![](https://media1.giphy.com/media/14sy6VGAd4BdKM/giphy.gif)

**Comment by Jpadilla1** [comment]
Feedback del pr #90 se puede encontrar aqui https://github.com/Code4PuertoRico/paravotar/pull/90#issuecomment-602276143. Podemos seguir trabajando este issue con varios PR's para no block el merge de #90

**Comment by froi** [comment]
Hey team @Code4PuertoRico/paravotar.

¿Qué tal este issue? Veo que un PR asociado esta _merged_. ¿Todavía esto es relevante?

**Comment by eluciano11** [comment]
Hey, entiendo que se puede cerrar el ticket pero aún faltaban par de issues con accesibilidad basado en el feedback que nos había dado Manolo. Creo que podemos trabajar eso en issues más específico en lugar de uno tan broad como este.

**Comment by eluciano11** [comment]
Closing for now.
