### ISSUE TITLE
Identificar cuales JIP's son para ciertas zonas vs cuales son para toda la isla

### ISSUE THREAD

**Issue by eluciano11** [Code4PuertoRico/paravotar#79]
Este ticket es un extracto de #60 en donde @rebelwarrior menciona lo siguiente:

>3. Las direcciones de los centros no indican cuales JIPs son para toda la isla (o sea que pueden recibir a alguien de toda la isla, como el que esta en Hato Rey en la comisión) comparados con los otros que no.

Una vez tengamos la lista de cuáles JIP's pueden atender a personas de toda la isla debemos identificarlas en el site.

**Comment by Jpadilla1** [comment]
Los encontre en el directorio http://www.ceepur.org/directorio.htm

Son los que dicen `Funciona bajo el concepto de JIP Isla**` en la seccion de servicios
