### ISSUE TITLE
Observaciones sobre requisitos

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/paravotar#81]
Angiemille Latorre nos envia las siguientes observaciones por Slack:

En realidad esto no tiene que estar separado. 

Es más “Nacido en Puerto Rico. Debes haber cumplido 18 años para la fecha del 3 de noviembre, 2020” 

Documento requerido:

- Ninguno 

Entonces le pondría:  “Para ir a la segura, puedes llevar uno o más de los siguientes documentos.

- Licencia (ideal)
- Certificado nacimiento original  (esto es sólo si con tu nombre y seguro social no sales en el sistema de registro demográfico) 

Nota importante: Lo que necesita la CEE es probar que naciste aquí. El pasaporte no hace eso así que no es necesario.

Entonces si pondría: “Debes saber:” 

- Nombre completo
- Dirección postal
- Dirección física
- Número de teléfono
- Número de seguro social
- Estatura y si quieres dejarlo listo para comunicaciones futuras:
- Email

Screenshot del documento original:
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/1918027/76543452-ea5db500-645c-11ea-9b59-24bd11f0342f.png">

PDF original:
[paravotar.pdf](https://github.com/Code4PuertoRico/paravotar/files/4325386/paravotar.pdf)

**Comment by froi** [comment]
Más feedback de Angiemille:

Seccion de __Naciste en un pais extrangejo__

Creo debe decir: “Naciste en un país extranjero y resides en Puerto Rico”

NOTA IMPORTANTE: 

Será elector de Puerto Rico todo ciudadano de los EEUU de y de Puerto Rico domiciliado legalmente en la jurisdicción de Puerto Rico y que a la fecha del evento electoral programado haya cumplido los dieciocho (18) años de edad.

Documento requerido (uno de ellos):

- Certificación del departamento de estado con acreditación
- Certificado de naturalización
- Pasaporte de los Estados Unidos vigente

Entonces le pondría:

“Para ir a la segura, puedes llevar uno o más de los siguientes documentos.
Licencia de Puerto Rico (ideal)

__Nota importante:__ Lo que necesita la CEE es probar que estás domiciliado legalmente.

Entonces si pondría: 

“Debes saber:”
- Nombre completo
- Dirección postal
- Dirección física
- Número de teléfono
- Número de seguro social
- Estatura

y si quieres dejarlo listo para comunicaciones futuras:
- Email”

__Screenshot__

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/1918027/76545094-8983ac00-645f-11ea-83db-bde1845e6437.png">

**Comment by froi** [comment]
Más feedback de Anigiemille:

Seccion __Naciste en los Estados Unidos, Continentales, Territorios o Posesiones:__

Naciste en EEUU / incluyendo cualquiera de sus territorios continentales o posesiones

__NOTA IMPORTANTE:__ Será elector de Puerto Rico todo ciudadano de los EEUU de y de Puerto Rico domiciliado legalmente en la jurisdicción de Puerto Rico y que a la fecha del evento electoral programado haya cumplido los dieciocho (18) años de edad.

Documento requerido (uno de ellos):

- Certificado nacimiento original
- Pasaporte vigente

Entonces le pondría:

Para ir a la segura, puedes llevar uno o más de los siguientes documentos.

- Licencia de Puerto Rico (ideal)

__Nota importante:__ Lo que necesita la CEE es probar que naciste en Puerto Rico.

Entonces si pondría: 

“Debes saber:”

- Nombre completo
- Dirección postal
- Dirección física
- Número de teléfono
- Número de seguro social
- Estatura

y si quieres dejarlo listo para comunicaciones futuras:

• Email

Screenshot original:

![image](https://user-images.githubusercontent.com/1918027/76545739-abc9f980-6460-11ea-9615-5c125ca104a9.png)

**Comment by ANGIEMILLE** [comment]
Aquí les paso Voto Ausente y Voto Adelantado de una vez
Disculpen que lo pase así todo por cantitos, pero es que me embollé con el primero y luego me dió verguenza seguirle añadiendo. En realidad tengo el cerebro frito hoy, pero les juro que yo no soy tan pendeja. Un abrazote 
[VOTO ADELANTADO.pdf](https://github.com/Code4PuertoRico/paravotar/files/4325647/VOTO.ADELANTADO.pdf)
[VOTO AUSENTE.pdf](https://github.com/Code4PuertoRico/paravotar/files/4325648/VOTO.AUSENTE.pdf)

**Comment by froi** [comment]
Gracias @angiemille :heart:

**Comment by eluciano11** [comment]
@ANGIEMILLE ya hicimos deploy a las recomendaciones de este issue:

Esto fue lo que cambiamos:
1. Eliminamos la tarjeta de personas que cumplen durante el cuatrenio.
2. A todas las tarjetas le añadimos la nota de que deben tener 18 años (o más) en o antes del 3 de noviembre de 2020.
3. Subimos de posición los documentos requeridos y los documentos que recomendamos que lleven.
4. Verificamos los documentos requeridos para personas que nacieron en US o territorios y para personas que nacieron en paises extranjeros.
5. Le hicimos update a los copies que describen a los tipos de votantes.

Creé dos issues para voto ausente (#86) y voto adelantado (#87).

Gracias por el feedback!
