### ISSUE TITLE
Translate site to English

### ISSUE THREAD

**Issue by eluciano11** [Code4PuertoRico/paravotar#84]
## Description
Este feature busca que el usuario pueda elegir ver el site en ingles o español. Para decidir qué lenguaje utilizar en el initial render podemos mirar el locale que el usuario esta utilizando en su teléfono o laptop. Si el local comienza con `en` mostramos el site en ingles, si comienza con `es` lo mostramos en español y si no comienza con ninguno de los dos podemos utilizar español como default (?). Después del initial render el usuario debe poder elegir el lenguaje de preferencia manualmente.

Entendemos que este feature se puede trabajar en tres partes:
1. Traducir el site en un Google Doc y pedir feedback on Slack o GitHub.
2. Añadir los locales al app y utilizar las funciones de traducción a través de todo el app.
3. Añadir un sección en el sidebar (o alguna parte del site) para que el usuario sepa en qué lenguaje estamos mostrando el site y pueda cambiar entre inglés y español.

No tenemos preferencia sobre la librería que se debe utilizar para manejar las traducciones. Adjunto varias opciones:

https://www.gatsbyjs.org/blog/2017-10-17-building-i18n-with-gatsby/
https://github.com/i18next/react-i18next

**Comment by davidbcruz** [comment]
Hello, I am a bilingual, English Dominant Puerto Rican at UCLA who is ready to help.

**Comment by jamesxv7** [comment]
Working on this. 

1. Traducir el site en un Google Doc y pedir feedback on Slack o GitHub.
https://docs.google.com/document/d/1EpoaynIOjGG6EfdPoeVwz6xwHpgCK0aWb3edF0lpKho/edit?usp=sharing

**Comment by jamesxv7** [comment]
Just a brief update to confirm I'm working on the right direction

![example-wip](https://user-images.githubusercontent.com/121668/84109529-e1936580-a9f0-11ea-9c77-25be2ebac4a6.gif)

https://github.com/jamesxv7/paravotar/tree/i18n

@eluciano11

**Comment by Jpadilla1** [comment]
This is great @jamesxv7! I like the overall direction of where the implementation is going and how the languages are being handled. I do have some questions:

1. Any reason why you chose to use `i18next`?
2. Any reason why we should have a `withTrans` HOC over having the provider be in a [root component](https://www.gatsbyjs.org/docs/browser-apis/#wrapRootElement)?

**Comment by jamesxv7** [comment]
> 1. Any reason why you chose to use `i18next`?

I use both, react-i18next and i18next. I found it more suitable for Gastby and is very well documented. 

> 2. Any reason why we should have a `withTrans` HOC over having the provider be in a [root component](https://www.gatsbyjs.org/docs/browser-apis/#wrapRootElement)?

I think the only reason is to be able to change language without executing a refresh of the page. But I'm not expert on Gatsby or React. 

I'm open to receive any feedback or guidance.

**Comment by jamesxv7** [comment]
@Jpadilla1 @froi 
I'm having a little trouble with the constants.ts file. I would like to discuss the issue with the team. What would be the best approach. Do the translations as part of the structure of the objects in the constants.ts file or migrate the texts to the structure of i18next translation.json?

Both options would heavily impact current components.

**Comment by Jpadilla1** [comment]
What kind of trouble is the constants.ts file causing? 

One thing to help is to discuss the pros/cons of each approach. They both seem to have the con of drastically changing components. Anything specific that you can call out on the pros on each approach?

**Comment by Jpadilla1** [comment]
> I think the only reason is to be able to change language without executing a refresh of the page. But I'm not expert on Gatsby or React.

The approach so far looks solid, seems that we can take advantage of the Gatsby wrapComponent API to avoid having multiple withTrans wrappers.

**Comment by jamesxv7** [comment]
> 
> 
> What kind of trouble is the constants.ts file causing?
> 
> One thing to help is to discuss the pros/cons of each approach. They both seem to have the con of drastically changing components. Anything specific that you can call out on the pros on each approach?


I'm basically trying to find out if I can do the translation with the result of the object. Maybe it is something that the library can do, I'm going to give more thought to this issue.

The main benefit I see from using the translation.json files is having everything in one place.

Regarding the use of the constants.ts file I cannot give much opinion since initially I do not know the architectural reasons for using this approach.

**Comment by jamesxv7** [comment]
@Jpadilla1 

Found a way to avoid heavily impact the structure of the constants.ts file and still able to translate without to much deviation from current structure in components. 

![example-wip1](https://user-images.githubusercontent.com/121668/84342824-88543f00-ab74-11ea-8d1a-5a5033d85a46.gif)

Refer to latest commit on i18n branch for example.

https://github.com/jamesxv7/paravotar/tree/i18n

**Comment by Jpadilla1** [comment]
I like this latest version a lot! Great work!!

**Comment by eluciano11** [comment]
@jamesxv7 I agree with @Jpadilla1, looks great!

**Comment by eluciano11** [comment]
@jamesxv7 question, would it be possible to do something like this: 

```
{
  ...
  recommendedDocsText: i18n.t("site.rec-docs"),
  ...
}
```

Instead of having the key and translating it on render?

Reference:
https://github.com/jamesxv7/paravotar/commit/045425550dafeba36dc5ad60d6f948140b00405b#diff-3492a40490f07203e59000caa268f46eR16

**Comment by jamesxv7** [comment]
@Jpadilla1 That will require transforming the constants.ts file into a component. 

Right now, we need to heavily impact the constants.ts file, adding logic to update state etc etc.  I think is possible but... when the user change the language will require a page refresh.

**Comment by eluciano11** [comment]
@jamesxv7 mejor no jaja

**Comment by jamesxv7** [comment]
@Jpadilla1 & @froi 

The translation is complete. At least for the items rendered to users. Refer to below branch for details.

https://github.com/jamesxv7/paravotar/tree/i18n

**Comment by eluciano11** [comment]
Hola @jamesxv7 👋 

Primero que todo, gracias por todo el trabajo que haz hecho! 

Miré el código y las traducciones y las veo bien. Tengo feedback sobre dos cosas:
1. No traduciría Comisione Estatal de Elecciones a State Elections Commission. Creo que es mejor usar los double quotes o italics.
2. Cambiaría la posición del translate button al sidebar en la version desktop y en mobile lo podemos poner al lado derecho del navbar.

Todo lo demás lo veo bien. Awesome job! 👏

**Comment by jamesxv7** [comment]
You welcome @eluciano11 

Respecto al ítem 2, no entendí bien la parte de moverlo a la derecha en la versión mobile, creo que quedaría muy justo, así que lo dejé abajo en ambas instancias. Cualquier comentario adicional se puede capturar en el review del PR.

¡A la orden siempre!

![example-wip2](https://user-images.githubusercontent.com/121668/85398381-222bcc80-b523-11ea-991c-43ebafd2fcab.gif)

**Comment by eluciano11** [comment]
Closing this issue, ya @jamesxv7 lo resolvió en #123. Muchas gracias por todo el esfuerzo y trabajo! 🙏
