### ISSUE TITLE
Revamp "Que debo llevar para obtener mi tarjeta electoral?"

### ISSUE THREAD

**Issue by Jpadilla1** [Code4PuertoRico/paravotar#94]
[Diseño Specs.pdf](https://github.com/Code4PuertoRico/paravotar/files/4422637/Diseno.Specs.pdf)
[Diseño Interractions.pdf](https://github.com/Code4PuertoRico/paravotar/files/4422638/Diseno.Interractions.pdf)

**Comment by eluciano11** [comment]
Pregunta, no necesitamos mover el focus de la pagina al recuadro nuevo cuando el usuario cambia de opción en el dropdown?

Feedback del diseño:
<img width="1458" alt="Screen_Shot_2020-04-03_at_8_04_04_AM" src="https://user-images.githubusercontent.com/6109151/78359044-3eeae080-7582-11ea-8584-375a8d3c3d5e.png">

<img width="1807" alt="Screen_Shot_2020-04-03_at_8_09_14_AM" src="https://user-images.githubusercontent.com/6109151/78359618-6a21ff80-7583-11ea-8704-921ee2f4198c.png">
